x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgres:
    image: postgres:15.6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 100000000
    logging: *logging

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_REALM_NAME: msp
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
      - ./keycloak/CustomKeycloakEvent-1.0-SNAPSHOT-jar-with-dependencies.jar:/opt/keycloak/providers/CustomKeycloakEvent-1.0-SNAPSHOT-jar-with-dependencies.jar
      - ./keycloak/keycloakScript.sh:/opt/keycloak/scripts/keycloakScript.sh
    logging: *logging
    entrypoint: "bash -c 'sleep 15 && /opt/keycloak/scripts/keycloakScript.sh'"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mspadmin"
      MONGO_INITDB_ROOT_PASSWORD: "adminPassword"
      MONGO_INITDB_DATABASE: "MSP"
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
